import type { Rule } from "markdownlint";

import { RULE_DOCS, getHeadingLevel } from "./utils.js";

/**
 * markdownlint rule: changeset-heading-hierarchy (CSH001)
 *
 * Validates heading structure in changeset files:
 * - No h1 headings allowed
 * - Headings must start at h2
 * - No depth skips (e.g., h2 ... h4 is invalid)
 */
export const HeadingHierarchyRule: Rule = {
	names: ["changeset-heading-hierarchy", "CSH001"],
	description: "Heading hierarchy must start at h2 with no h1 or depth skips",
	tags: ["changeset"],
	parser: "micromark",
	function: function CSH001(params, onError) {
		let prevDepth = 0;

		for (const token of params.parsers.micromark.tokens) {
			if (token.type !== "atxHeading") {
				continue;
			}

			const depth = getHeadingLevel(token);

			if (depth === 1) {
				onError({
					lineNumber: token.startLine,
					detail: `h1 headings are not allowed in changeset files. Use h2 (##) for top-level sections like "## Features" or "## Bug Fixes". h1 is reserved for the version title generated by the changelog formatter. See: ${RULE_DOCS.CSH001}`,
				});
				continue;
			}

			if (prevDepth > 0 && depth > prevDepth + 1) {
				onError({
					lineNumber: token.startLine,
					detail: `Heading level skipped: expected h${prevDepth + 1} or lower, found h${depth}. Headings must increase sequentially (h2 → h3 → h4). Add the missing intermediate level or reduce this heading's depth. See: ${RULE_DOCS.CSH001}`,
				});
			}

			prevDepth = depth;
		}
	},
};
