/**
 * Remark-lint rule: changeset-heading-hierarchy
 *
 * Validates heading structure in changeset files:
 * - No h1 headings allowed
 * - Headings must start at h2
 * - No depth skips (e.g., h2 → h4 is invalid)
 *
 */

import type { Heading, Root } from "mdast";
import { lintRule } from "unified-lint-rule";
import { visit } from "unist-util-visit";
import { RULE_DOCS } from "../../markdownlint/rules/utils.js";

export const HeadingHierarchyRule = lintRule("remark-lint:changeset-heading-hierarchy", (tree: Root, file) => {
	let prevDepth = 0;

	visit(tree, "heading", (node: Heading) => {
		if (node.depth === 1) {
			file.message(
				`h1 headings are not allowed in changeset files. Use h2 (##) for top-level sections like "## Features" or "## Bug Fixes". h1 is reserved for the version title generated by the changelog formatter. See: ${RULE_DOCS.CSH001}`,
				node,
			);
			return;
		}

		if (prevDepth > 0 && node.depth > prevDepth + 1) {
			file.message(
				`Heading level skipped: expected h${prevDepth + 1} or lower, found h${node.depth}. Headings must increase sequentially (h2 → h3 → h4). Add the missing intermediate level or reduce this heading's depth. See: ${RULE_DOCS.CSH001}`,
				node,
			);
		}

		prevDepth = node.depth;
	});
});
